#ifndef UN260_MANROPE_FONTS_H
#define UN260_MANROPE_FONTS_H

#include "lvgl/lvgl.h"

LV_FONT_DECLARE(lv_font_manrope_bold_10);
LV_FONT_DECLARE(lv_font_manrope_bold_12);
LV_FONT_DECLARE(lv_font_manrope_bold_14);
LV_FONT_DECLARE(lv_font_manrope_bold_16);
LV_FONT_DECLARE(lv_font_manrope_bold_18);
LV_FONT_DECLARE(lv_font_manrope_bold_20);
LV_FONT_DECLARE(lv_font_manrope_bold_22);
LV_FONT_DECLARE(lv_font_manrope_bold_24);
LV_FONT_DECLARE(lv_font_manrope_bold_28);
LV_FONT_DECLARE(lv_font_manrope_bold_30);
LV_FONT_DECLARE(lv_font_manrope_bold_32);
LV_FONT_DECLARE(lv_font_manrope_bold_40);
LV_FONT_DECLARE(lv_font_manrope_bold_42);
LV_FONT_DECLARE(lv_font_manrope_bold_44);
LV_FONT_DECLARE(lv_font_manrope_bold_48);

LV_FONT_DECLARE(lv_font_manrope_extrabold_10);
LV_FONT_DECLARE(lv_font_manrope_extrabold_12);
LV_FONT_DECLARE(lv_font_manrope_extrabold_14);
LV_FONT_DECLARE(lv_font_manrope_extrabold_16);
LV_FONT_DECLARE(lv_font_manrope_extrabold_18);
LV_FONT_DECLARE(lv_font_manrope_extrabold_20);
LV_FONT_DECLARE(lv_font_manrope_extrabold_22);
LV_FONT_DECLARE(lv_font_manrope_extrabold_24);
LV_FONT_DECLARE(lv_font_manrope_extrabold_28);
LV_FONT_DECLARE(lv_font_manrope_extrabold_30);
LV_FONT_DECLARE(lv_font_manrope_extrabold_32);
LV_FONT_DECLARE(lv_font_manrope_extrabold_40);
LV_FONT_DECLARE(lv_font_manrope_extrabold_42);
LV_FONT_DECLARE(lv_font_manrope_extrabold_44);
LV_FONT_DECLARE(lv_font_manrope_extrabold_48);

LV_FONT_DECLARE(lv_font_instrument_sans_bold_10);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_12);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_14);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_16);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_18);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_20);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_22);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_24);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_28);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_30);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_32);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_40);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_42);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_44);
LV_FONT_DECLARE(lv_font_instrument_sans_bold_48);

LV_FONT_DECLARE(lv_font_instrument_sans_medium_10);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_12);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_14);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_16);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_18);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_20);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_22);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_24);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_28);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_30);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_32);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_40);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_42);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_44);
LV_FONT_DECLARE(lv_font_instrument_sans_medium_48);

LV_FONT_DECLARE(lv_font_instrument_sans_semibold_10);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_12);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_14);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_16);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_18);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_20);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_22);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_24);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_28);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_30);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_32);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_40);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_42);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_44);
LV_FONT_DECLARE(lv_font_instrument_sans_semibold_48);

#endif
