#ifndef LV_PAGE_DECLEAR_H
#define LV_PAGE_DECLEAR_H
#include"page_01_main.h"
#include"page_02_list.h"
#include"page_03_menu.h"
#include"page_05_set_password.h"
#include"page_06_settings.h"
#include"page_07_curr.h"
#include"page_08_boot.h"
#include"page_09_cis_cala.h"
#include"page_10_debug.h"
#include"page_11_timeset.h"
#include"page_12_sensor.h"
#include"page_13_upgrade.h"
#include"page_14_main_upgrade.h"
#include"page_15_image_upgrade.h"
#include"page_16_ui_upgrade.h"
#include "page_17_motor_test.h"
#include "page_18_pure.h"
#include "page_19_history.h"
#include "page_20_set_print.h"
#include "page_21_set_language.h"
#include "page_22_set_double_note.h"
#include "page_23_set_flap.h"
#include "page_24_set_reject_pocket.h"
#include "page_25_set_serial_number.h"
#include "page_26_set_aging.h"
#include "page_27_set_cfd_level.h"
#include "page_28_get_image.h"
#include "page_29_set_password.h"
#include "page_30_set_factory.h"
#include "page_31_get_wave.h"
#include "page_00_boot_anim.h"

#endif // !LV_PAGE_DECLEAR_H
