#ifndef PROTOCOL_FRAME_H
#define PROTOCOL_FRAME_H

#define PROTOCOL_FRAME_HEADER_FIRST   0xFD
#define PROTOCOL_FRAME_HEADER_SECOND  0xDF
#define PROTOCOL_FRAME_TRAILER         0x0A
#define PROTOCOL_FRAME_PAYLOAD_OFFSET  4
#define PROTOCOL_FRAME_OVERHEAD        5
#define PROTOCOL_FRAME_MIN_SIZE        PROTOCOL_FRAME_OVERHEAD
#define PROTOCOL_FRAME_MAX_SIZE        0xFF
#define PROTOCOL_FRAME_MAX_PAYLOAD     \
    (PROTOCOL_FRAME_MAX_SIZE - PROTOCOL_FRAME_OVERHEAD)

#endif
