#ifndef UI_TEXT_H
#define UI_TEXT_H

#include "un260/lv_system/lv_str.h"

typedef struct {
    const char* en;
    const char* cn;
    const char* kr;
} ui_text_item_t;

typedef enum {
    UI_TEXT_PAGE16_TITLE = 0,
    UI_TEXT_PAGE16_ESC,
    UI_TEXT_PAGE16_USB_STATUS_FMT,
    UI_TEXT_PAGE16_USB_INSERTED,
    UI_TEXT_PAGE16_USB_NOT_INSERTED,
    UI_TEXT_PAGE16_FILE_STATUS_FMT,
    UI_TEXT_PAGE16_MOUNT_OK,
    UI_TEXT_PAGE16_MOUNT_NOT,
    UI_TEXT_PAGE16_PACKAGE_FOUND,
    UI_TEXT_PAGE16_PACKAGE_NOT_FOUND,
    UI_TEXT_PAGE16_HINT_INSERT_USB,
    UI_TEXT_PAGE16_HINT_INSERTED_CLICK_UPGRADE,
    UI_TEXT_PAGE16_HINT_MISSING_PACKAGE,
    UI_TEXT_PAGE16_HINT_READY,
    UI_TEXT_PAGE16_HINT_UPGRADING_WAIT,
    UI_TEXT_PAGE16_HINT_UPGRADING_WAIT_FMT,
    UI_TEXT_PAGE16_HINT_FINISHED,
    UI_TEXT_PAGE16_HINT_FAILED,
    UI_TEXT_PAGE16_HINT_NO_USB,
    UI_TEXT_PAGE16_HINT_AUTO_MOUNT_FAILED,
    UI_TEXT_PAGE16_HINT_START_SCRIPT_FAILED,
    UI_TEXT_PAGE16_UPGRADE_BTN,
    UI_TEXT_PAGE16_POWER_OFF,
    UI_TEXT_PAGE16_POWER_OFF_LONG,
    UI_TEXT_PAGE_MAX,

    UI_TEXT_WIDGET_BASE = 200,
    UI_TEXT_WIDGET_UPGRADE_POPUP_TAG = UI_TEXT_WIDGET_BASE,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROMPT_TITLE,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROMPT_DESC,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROMPT_BTN_CANCEL,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROMPT_BTN_CONFIRM,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROGRESS_TITLE,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROGRESS_DESC,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROGRESS_STEP_VERIFY,
    UI_TEXT_WIDGET_UPGRADE_POPUP_PROGRESS_STEP_VERIFY_FAIL,
    UI_TEXT_WIDGET_UPGRADE_POPUP_SUCCESS_TITLE,
    UI_TEXT_WIDGET_UPGRADE_POPUP_SUCCESS_DESC,
    UI_TEXT_WIDGET_UPGRADE_POPUP_SUCCESS_BTN_LATER,
    UI_TEXT_WIDGET_UPGRADE_POPUP_SUCCESS_BTN_CONFIRM,
    UI_TEXT_WIDGET_UPGRADE_POPUP_FAIL_TITLE,
    UI_TEXT_WIDGET_UPGRADE_POPUP_FAIL_DESC,
    UI_TEXT_WIDGET_UPGRADE_POPUP_FAIL_BTN_RETRY,
    UI_TEXT_WIDGET_UPGRADE_POPUP_FAIL_START_SCRIPT,
    UI_TEXT_WIDGET_PRINT_TOAST_PRINTING,
    UI_TEXT_WIDGET_PRINT_TOAST_COUNT_FIRST,
    UI_TEXT_MAX
} ui_text_id_t;

const char* ui_text_get(ui_text_id_t text_id); //统一获取当前语言文本

#endif
