#ifndef LV_UPGRADE_POPUP_TEXT_H
#define LV_UPGRADE_POPUP_TEXT_H

typedef enum {
    UPGRADE_POPUP_TEXT_TAG = 0,
    UPGRADE_POPUP_TEXT_PROMPT_TITLE,
    UPGRADE_POPUP_TEXT_PROMPT_DESC,
    UPGRADE_POPUP_TEXT_PROMPT_BTN_CANCEL,
    UPGRADE_POPUP_TEXT_PROMPT_BTN_CONFIRM,
    UPGRADE_POPUP_TEXT_PROGRESS_TITLE,
    UPGRADE_POPUP_TEXT_PROGRESS_DESC,
    UPGRADE_POPUP_TEXT_PROGRESS_STEP_VERIFY,
    UPGRADE_POPUP_TEXT_PROGRESS_STEP_VERIFY_FAIL,
    UPGRADE_POPUP_TEXT_SUCCESS_TITLE,
    UPGRADE_POPUP_TEXT_SUCCESS_DESC,
    UPGRADE_POPUP_TEXT_SUCCESS_BTN_LATER,
    UPGRADE_POPUP_TEXT_SUCCESS_BTN_CONFIRM,
    UPGRADE_POPUP_TEXT_FAIL_TITLE,
    UPGRADE_POPUP_TEXT_FAIL_DESC,
    UPGRADE_POPUP_TEXT_FAIL_BTN_RETRY,
    UPGRADE_POPUP_TEXT_FAIL_START_SCRIPT,
    UPGRADE_POPUP_TEXT_MAX
} upgrade_popup_text_id_t;

const char* lv_upgrade_popup_text_get(upgrade_popup_text_id_t text_id); //获取升级弹窗当前语言文本

#endif
